; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    https://github.com/lvgl/lvgl.git#v8.3.11
	; tomstewart89/BasicLinearAlgebra
	; https://github.com/adafruit/Adafruit_Si7021.git
	; https://github.com/adafruit/adafruit_sensor.git
	adafruit/Adafruit BusIO
	https://github.com/adafruit/Adafruit_VL6180X.git


build_flags =
    -D USER_SETUP_LOADED=1
    ; CYD ILI9341 Pinout configuratie
    -D ILI9341_2_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=55000000
    -D SPI_READ_FREQUENCY=20000000