// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>

void cb_click_red_button(lv_event_t * e)
{
	// Your code here
}

void btn_click_action(lv_event_t * e)
{
    printf("Knop geklikt op het CYD scherm!\n");
	
}
